version: '3.7'
services:
  redis-slave:
    container_name: cocktail-io-redis-sentinel-slave
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=cocktail-io-redis-sentinel-master
      - REDIS_MASTER_PASSWORD=cocktail
      - REDIS_PASSWORD=cocktail
    ports:
      - "6381:6379"
