version: '3.7'
services:
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    container_name: cocktail-io-redis-sentinel-1
    environment:
      - REDIS_MASTER_SET=my-master
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PASSWORD=cocktail
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    ports:
      - "26379:26379"
