version: '3'
services:
  mongodb:
    container_name: cocktail-io-local-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cocktail-io
      MONGO_INITDB_ROOT_PASSWORD: cocktail-io
  mongo-express:
    container_name: my-mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cocktail-io
      ME_CONFIG_MONGODB_ADMINPASSWORD: cocktail-io
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: cocktail-io
      ME_CONFIG_BASICAUTH_PASSWORD: cocktail-io
    depends_on:
      - mongodb
