version: '3.7'
services:
  phpmyadmin:
    container_name: cocktail-io-local-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: cocktail-io-local-mysql
      MYSQL_ROOT_PASSWORD: cocktail-io
    ports:
      - '8083:80'
