version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: cocktail-io-local-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

