version: '3.7'
services:
  zoo:
    container_name: cocktail-io-zoo
    image: zookeeper
    restart: always
    hostname: zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
